version: "3.9"

services:
  ubuntu20:
    image: ubuntu:20.04
    container_name: ubuntu_20
    restart: unless-stopped
    command: bash -c "while true; do sleep 3600; done"
    tty: true
    stdin_open: true
    volumes:
      - ./data20:/data
